"""empty message

Revision ID: 3b7c16ddfa09
Revises: 35ec0ba2b765
Create Date: 2019-06-27 12:37:46.197082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b7c16ddfa09'
down_revision = '35ec0ba2b765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('selected_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_selected_user_username'), 'selected_user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_selected_user_username'), table_name='selected_user')
    op.drop_table('selected_user')
    # ### end Alembic commands ###
