"""empty message

Revision ID: 9dc2af2810b8
Revises: e0f5170d38e3
Create Date: 2019-06-27 20:11:19.130324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dc2af2810b8'
down_revision = 'e0f5170d38e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'recieved')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('recieved', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
