"""empty message

Revision ID: e0f5170d38e3
Revises: 3b7c16ddfa09
Create Date: 2019-06-27 20:05:46.230721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0f5170d38e3'
down_revision = '3b7c16ddfa09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('recieved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'recieved')
    # ### end Alembic commands ###
